[package]
name = "lfr_core"
version = "0.5.9"
edition = "2021"

[dependencies]
windows-sys = { version = "0.52", features = [
    "Win32_UI_WindowsAndMessaging",
    "Win32_Foundation",
    "Win32_Graphics_Gdi"
] }